name: Deploy
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run deploy hook
      run: curl -s ${{ secrets.DEPLOY_HOOK }}